/*
 * Service worker — generated by tools/build_web.py. Do not edit by hand.
 *
 * Cache-first over a precached shell, so the app opens instantly and works with
 * no connection at all. CACHE is stamped with a hash of the content and source,
 * so publishing a change rolls the cache over instead of serving a stale build.
 */

const CACHE = 'gruezi-48a0ca9d5b8d';
const PRECACHE = [
  ".",
  "index.html",
  "app.css",
  "manifest.webmanifest",
  "assets/fonts/nunito-var.woff2",
  "icons/icon-192.png",
  "icons/icon-512.png",
  "icons/apple-touch-icon.png",
  "icons/favicon-64.png",
  "js/app.js",
  "js/srs.js",
  "js/store.js",
  "js/repo.js",
  "js/ui.js",
  "js/icons.js",
  "js/lang.js",
  "js/pace.js",
  "js/backup.js",
  "js/views/daily.js",
  "js/views/learn.js",
  "js/views/bridges.js",
  "data/gruezi/sentences.json",
  "data/gruezi/bridges.json",
  "data/gruezi/lessons.json",
  "data/hoi/sentences.json",
  "data/hoi/bridges.json",
  "data/hoi/lessons.json",
  "data/ciao/sentences.json",
  "data/ciao/bridges.json",
  "data/ciao/lessons.json",
  "data/shalom/sentences.json",
  "data/shalom/bridges.json",
  "data/shalom/lessons.json"
];

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE)
      .then((cache) => cache.addAll(PRECACHE))
      .then(() => self.skipWaiting()),
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (event) => {
  const { request } = event;
  if (request.method !== 'GET') return;

  event.respondWith(
    caches.match(request).then((hit) => {
      if (hit) return hit;
      return fetch(request)
        .then((response) => {
          // Cache same-origin successes as they're fetched, so anything missed
          // by the precache list still works offline next time.
          if (response.ok && new URL(request.url).origin === self.location.origin) {
            const copy = response.clone();
            caches.open(CACHE).then((cache) => cache.put(request, copy));
          }
          return response;
        })
        .catch(() => {
          // Offline and not cached: a navigation still gets the app shell.
          if (request.mode === 'navigate') return caches.match('index.html');
          return Response.error();
        });
    }),
  );
});
